name: demo-feedback

on:
  push:
    branches:
    - main
    paths:
    - project/**

jobs:
  project-feedback/CI Implementation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main
    

    
    # Run Continuous Integration
    - name: CI Test
      run: |
        ./project/tests.sh

  
