name: demo-feedback

on:
  push:
    branches:
    - main
  

jobs:
  CI_Implementation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main
        
   # Install python
   
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

  # Run Continuous Integration
    - name: CI Test
      run: |
       chmod u+r+x ./main/project/tests.sh
       cd ./main/project
       ./tests.sh
      

        
